#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t svn_proplist.XXXXXX`

svn proplist -v $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS > $LOGFILE 2>&1
unset WINDOWID
zenity --text-info --title="Subversion: Properties" --filename=$LOGFILE --width=600 --height=400
rm -f $LOGFILE
