#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t svn_revert.XXXXXX`

if [ -z $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ] ; then
    svn revert . > $LOGFILE 2>&1
else
    svn revert "$@" > $LOGFILE 2>&1
fi

unset WINDOWID
zenity --text-info --title="Subversion: Revert" --filename=$LOGFILE --width=600 --height=400
rm -f $LOGFILE
